/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorModificarEstudiante;
import Modelo.RegistroCursos;
import Modelo.RegistroEstudiantes;
import Modelo.RegistroMatricula;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class Menu extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Menu
     */
    VentanaRegistroEstudiante ventanaRegistro;
    VentanaModificarEstudiante ventanaModificar;
    VentanaEliminarEstudiante ventanaEliminar;
    VentanaConsultarEstudiantes ventanaConsultarEstudiante;
    VentanaRegistroCurso ventanaRegistroCurso;
    VentanaModificarCurso ventanaModificarCurso;
    VentanaEliminarCursos ventanaEliminarCursos;
    VentanaConsultarCursos ventanaConsultarCursos;
    VentanaMatricula ventanaMatricula;
    VentanaReportes ventanaReportes;
    ControladorModificarEstudiante controladorModificarEstudiante;
    RegistroEstudiantes registroEstudiantes = new RegistroEstudiantes();
    RegistroCursos registroCursos = new RegistroCursos();
    RegistroMatricula registroMatricula =new RegistroMatricula();
    public Menu() {
        initComponents();
        jmiConsultarCursos.addActionListener(this);
        jmiConsultarEstudiantes.addActionListener(this);
        jmiEliminarCursos.addActionListener(this);
        jmiEliminarEstudiante.addActionListener(this);
        jmiModificarCursos.addActionListener(this);
        jmiModificarEstudiante.addActionListener(this);
        jmiProcesoDeMatricula.addActionListener(this);
        jmiRegistrarCursos.addActionListener(this);
        jmiRegistrarEstudiante.addActionListener(this);
        jmiReportes.addActionListener(this);
        jmiSalir.addActionListener(this);
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmEstudiantes = new javax.swing.JMenu();
        jmiRegistrarEstudiante = new javax.swing.JMenuItem();
        jmiModificarEstudiante = new javax.swing.JMenuItem();
        jmiEliminarEstudiante = new javax.swing.JMenuItem();
        jmiConsultarEstudiantes = new javax.swing.JMenuItem();
        jmiProcesoDeMatricula = new javax.swing.JMenuItem();
        jmCursos = new javax.swing.JMenu();
        jmiRegistrarCursos = new javax.swing.JMenuItem();
        jmiModificarCursos = new javax.swing.JMenuItem();
        jmiEliminarCursos = new javax.swing.JMenuItem();
        jmiConsultarCursos = new javax.swing.JMenuItem();
        jmiReportes = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de registro UCR");
        setBackground(new java.awt.Color(255, 255, 255));

        lbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/logoUCR.png"))); // NOI18N

        jMenuBar1.setToolTipText("sd");

        jmEstudiantes.setText("Estudiantes");

        jmiRegistrarEstudiante.setText("Registrar estudiante");
        jmEstudiantes.add(jmiRegistrarEstudiante);

        jmiModificarEstudiante.setText("Modificar Estudiante");
        jmEstudiantes.add(jmiModificarEstudiante);

        jmiEliminarEstudiante.setText("Eliminar estudiante");
        jmEstudiantes.add(jmiEliminarEstudiante);

        jmiConsultarEstudiantes.setText("Consultar estudiantes");
        jmEstudiantes.add(jmiConsultarEstudiantes);

        jmiProcesoDeMatricula.setText("Proceso de matrícula");
        jmEstudiantes.add(jmiProcesoDeMatricula);

        jMenuBar1.add(jmEstudiantes);

        jmCursos.setText("Cursos");

        jmiRegistrarCursos.setText("Registrar cursos");
        jmCursos.add(jmiRegistrarCursos);

        jmiModificarCursos.setText("Modificar cursos");
        jmCursos.add(jmiModificarCursos);

        jmiEliminarCursos.setText("Eliminar cursos");
        jmCursos.add(jmiEliminarCursos);

        jmiConsultarCursos.setText("Consultar cursos");
        jmCursos.add(jmiConsultarCursos);

        jmiReportes.setText("Reportes");
        jmCursos.add(jmiReportes);

        jMenuBar1.add(jmCursos);

        jmSalir.setText("Salir");

        jmiSalir.setText("Salir del sistema");
        jmSalir.add(jmiSalir);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCursos;
    private javax.swing.JMenu jmEstudiantes;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiConsultarCursos;
    private javax.swing.JMenuItem jmiConsultarEstudiantes;
    private javax.swing.JMenuItem jmiEliminarCursos;
    private javax.swing.JMenuItem jmiEliminarEstudiante;
    private javax.swing.JMenuItem jmiModificarCursos;
    private javax.swing.JMenuItem jmiModificarEstudiante;
    private javax.swing.JMenuItem jmiProcesoDeMatricula;
    private javax.swing.JMenuItem jmiRegistrarCursos;
    private javax.swing.JMenuItem jmiRegistrarEstudiante;
    private javax.swing.JMenuItem jmiReportes;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JLabel lbImagen;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void actionPerformed(ActionEvent evento) {
        if (evento.getSource() == jmiRegistrarEstudiante) {
            ventanaRegistro = new VentanaRegistroEstudiante();
            ventanaRegistro.init(registroEstudiantes);
            ventanaRegistro.setVisible(true);
        }
        if (evento.getSource() == jmiModificarEstudiante) {
            ventanaModificar = new VentanaModificarEstudiante();
            ventanaModificar.init(registroEstudiantes);
            ventanaModificar.setVisible(true);
        }
        if (evento.getSource() == jmiEliminarEstudiante) {
            ventanaEliminar = new VentanaEliminarEstudiante();
            ventanaEliminar.init(registroEstudiantes);
            ventanaEliminar.setVisible(true);
        }
        if (evento.getSource() == jmiConsultarEstudiantes) {
            ventanaConsultarEstudiante = new VentanaConsultarEstudiantes();
            ventanaConsultarEstudiante.init(registroEstudiantes);
            ventanaConsultarEstudiante.setVisible(true);
        }
        if (evento.getSource() == jmiRegistrarCursos) {
            ventanaRegistroCurso = new VentanaRegistroCurso();
            ventanaRegistroCurso.init(registroCursos);
            ventanaRegistroCurso.setVisible(true);
        }
        if (evento.getSource() == jmiModificarCursos) {
            ventanaModificarCurso = new VentanaModificarCurso();
            ventanaModificarCurso.init(registroCursos);
            ventanaModificarCurso.setVisible(true);
        }
        if (evento.getSource() == jmiEliminarCursos) {
            ventanaEliminarCursos = new VentanaEliminarCursos();
            ventanaEliminarCursos.init(registroCursos);
            ventanaEliminarCursos.setVisible(true);
        }
        if (evento.getSource() == jmiConsultarCursos) {
            ventanaConsultarCursos = new VentanaConsultarCursos();
            ventanaConsultarCursos.init(registroCursos);
            ventanaConsultarCursos.setVisible(true);
        }
        if(evento.getSource()==jmiProcesoDeMatricula){
            ventanaMatricula= new VentanaMatricula();
            ventanaMatricula.init(registroEstudiantes, registroCursos, registroMatricula);
            ventanaMatricula.setVisible(true);
        }
        if(evento.getSource()==jmiReportes){
            ventanaReportes = new VentanaReportes();
            ventanaReportes.init(registroMatricula);
            ventanaReportes.setVisible(true);
        }
        if (evento.getSource() == jmiSalir) {
            JOptionPane.showMessageDialog(null, "Hasta pronto");
            System.exit(0);
        }
    }
}
