/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.RegistroEstudiantes;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class PanelConsultarEstudiantes extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarEstudiantes
     */
    public static final String BOTON_CONSULTAR_ESTUDIANTE = "Consultar carnet";
    public static final String BOTON_CONSULTAR_ESTUDIANTES = "Consultar estudiantes";
    public static final String BOTON_CANCELAR = "Cancelar";
    public static final String BOTON_BORRAR_DATOS = "Borrar datos";

    public PanelConsultarEstudiantes() {
        initComponents();
        jtaEstudiantesConsultados.setEditable(false);
        jbConsultarEstudiante.setText(BOTON_CONSULTAR_ESTUDIANTE);
        jbBorrarDatos.setText(BOTON_BORRAR_DATOS);
        jbCancelar.setText(BOTON_CANCELAR);
        jbConsultarEstudiantes.setText(BOTON_CONSULTAR_ESTUDIANTES);
    }

    public void consultaEstudiante(RegistroEstudiantes registroEstudiantes) {
        jtaEstudiantesConsultados.setText(registroEstudiantes.retornarEstudiante(jtCarnet.getText()));
    }

    public void consultaEstudiantes(RegistroEstudiantes registroEstudiantes) {
        jtaEstudiantesConsultados.setText(registroEstudiantes.getInformacion());
    }

    public void setManejador(ActionListener controladorConsultaEstudiante) {
        jbConsultarEstudiante.addActionListener(controladorConsultaEstudiante);
        jbConsultarEstudiantes.addActionListener(controladorConsultaEstudiante);
        jbBorrarDatos.addActionListener(controladorConsultaEstudiante);
        jbCancelar.addActionListener(controladorConsultaEstudiante);
    }

    public void borrarDatos() {
        jtaEstudiantesConsultados.setText("");
        jtCarnet.setText("");
    }

    public String getCarnet() {
        return jtCarnet.getText();
    }

    public void msjDigiteCarnet() {
        JOptionPane.showMessageDialog(null, "Digite un carnet válido", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjNoEntrado() {
        JOptionPane.showMessageDialog(null, "No se ha encontrado el estudiante consultado", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjArrayVacio() {
        JOptionPane.showMessageDialog(null, "No existen estudiantes en el sistema");
    }

    public void msjBorraCarnet() {
        JOptionPane.showMessageDialog(null, "Por favor borre el carnet para continuar", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCarnet = new javax.swing.JLabel();
        jtCarnet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbConsultarEstudiantes = new javax.swing.JButton();
        jbConsultarEstudiante = new javax.swing.JButton();
        jScBarra = new javax.swing.JScrollPane();
        jtaEstudiantesConsultados = new javax.swing.JTextArea();
        jbBorrarDatos = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        jlCarnet.setText("Carnet");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel2.setText("Consultar estudiantes");

        jbConsultarEstudiantes.setText("Consultar estudiantes");

        jbConsultarEstudiante.setText("Consultar estudiante");

        jtaEstudiantesConsultados.setColumns(20);
        jtaEstudiantesConsultados.setRows(5);
        jScBarra.setViewportView(jtaEstudiantesConsultados);

        jbBorrarDatos.setText("Borrar datos");

        jbCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbConsultarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbConsultarEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbBorrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jScBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScBarra)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbConsultarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbConsultarEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScBarra;
    private javax.swing.JButton jbBorrarDatos;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConsultarEstudiante;
    private javax.swing.JButton jbConsultarEstudiantes;
    private javax.swing.JLabel jlCarnet;
    private javax.swing.JTextField jtCarnet;
    private javax.swing.JTextArea jtaEstudiantesConsultados;
    // End of variables declaration//GEN-END:variables
}
