/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Matricula;
import Modelo.RegistroCursos;
import Modelo.RegistroEstudiantes;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class PanelMatricula extends javax.swing.JPanel {

    /**
     * Creates new form PanelMatrcula
     */
    public PanelMatricula() {
        initComponents();
        jtFecha.setEditable(false);
        jtNombre.setEditable(false);
        setFecha();
    }

    public Matricula retornarMatricula(RegistroCursos registroCursos) {
        Matricula matricula;
        matricula = new Matricula(jtFecha.getText(), jtNombre.getText(), jtCarnet.getText(), retornarCursoSeleccionado(), registroCursos.retornarSiglas(retornarCursoSeleccionado()), registroCursos.retornarCreditosNombre(retornarCursoSeleccionado()));//NECESITO NOMBRE DEL CURSO
        return matricula;
    }

    public void llenarCursoCombo(RegistroCursos registroCursos) {
        for (int i = 0; i < registroCursos.retornarTamano(); i++) {
            jcbCurso.addItem(registroCursos.retornarCursoCombo(i));
        }
    }

    public String retornarCursoSeleccionado() {
        String curso = (String) jcbCurso.getSelectedItem();
        return curso;
    }

    public void setFecha() {
        Calendar fecha = new GregorianCalendar();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        mes++;
        jtFecha.setText(dia + " / " + mes + " / " + año);
    }

    public void consultaEstudiante(RegistroEstudiantes registroEstudiantes) {
        jtNombre.setText(registroEstudiantes.retornarNombre(jtCarnet.getText()));
    }

    public String getCarnet() {
        return jtCarnet.getText();
    }

    public void msjEstNoEncontrado() {
        JOptionPane.showMessageDialog(null, "No se ha encontrado el estudiante", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjDigiteCarntet() {
        JOptionPane.showMessageDialog(null, "Por favor digite el carnet previamente", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjRealiceBusqueda() {
        JOptionPane.showMessageDialog(null, "Por favor realice una busqueda del estudiante previamente", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjMatriculaConsolidada() {
        JOptionPane.showMessageDialog(null, "La matrícula se consolidó exitosamente");
    }

    public void msjYaEstaEnElCurso() {
        JOptionPane.showMessageDialog(null, "Este estudiante ya se encuentra matriculado en el curso seleccionado", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjNoHayCursos() {
        JOptionPane.showMessageDialog(null, "Por favor ingrese algún curso al sistema", "No hay cursos", JOptionPane.INFORMATION_MESSAGE);
    }

    public void borrarTxt() {
        jtCarnet.setText("");
        jtNombre.setText("");
    }

    public String retornarNombre() {
        return jtNombre.getText();
    }

    public void desHabilitarCarnet() {
        jtCarnet.setEditable(false);
    }

    public void habilitarCarnet() {
        jtCarnet.setEditable(true);
    }

    public boolean verificarComboVacio() {
        boolean verifica = false;
        if (jcbCurso.getSelectedIndex() == -1) {
            verifica=true;
        }
        return verifica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMatricula = new javax.swing.JLabel();
        jlCurso = new javax.swing.JLabel();
        jcbCurso = new javax.swing.JComboBox();
        jlCarnet = new javax.swing.JLabel();
        jtCarnet = new javax.swing.JTextField();
        jlNombre = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jlFecha = new javax.swing.JLabel();
        jtFecha = new javax.swing.JTextField();

        jlMatricula.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jlMatricula.setText("Matrícula de estudiantes");

        jlCurso.setText("Seleccione el curso");

        jcbCurso.setMaximumRowCount(5);

        jlCarnet.setText("Carnet del estudiante");

        jlNombre.setText("Nombre");

        jlFecha.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jlMatricula))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCarnet)
                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcbCurso;
    private javax.swing.JLabel jlCarnet;
    private javax.swing.JLabel jlCurso;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextField jtCarnet;
    private javax.swing.JTextField jtFecha;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
