/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class PanelDatosEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatosEstudiante
     */
    public PanelDatosEstudiante() {
        initComponents();
    }

    public String getNombre() {
        return jtNombre.getText();
    }

    public String getCarnet() {
        return jtCarnet.getText();
    }

    public void borrarTxt() {
        jtNombre.setText("");
        jtCarnet.setText("");
    }

    public void msjAgregadoExito() {
        JOptionPane.showMessageDialog(null, "El estudiante se agregó exitosamente");
    }

    public void msjEstYaRegistrado() {
        JOptionPane.showMessageDialog(null, "Ya existe un estudiante con este numero de carnet", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjPedirTodosDatos() {
        JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos del estudiante", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRegistroEstudiantes = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbCarnet = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtCarnet = new javax.swing.JTextField();

        lbRegistroEstudiantes.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lbRegistroEstudiantes.setText("Registrar estudiante");

        lbNombre.setText("Nombre");

        lbCarnet.setText("Carnet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(lbCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lbRegistroEstudiantes)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbRegistroEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jtCarnet;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JLabel lbCarnet;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbRegistroEstudiantes;
    // End of variables declaration//GEN-END:variables
}
