/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class PanelBusquedaCurso extends javax.swing.JPanel {

    /**
     * Creates new form PanelBusquedaCurso
     */
    public PanelBusquedaCurso() {
        initComponents();
    }

    public String getSiglas() {
        return jtSiglas.getText();
    }

    public String getNombre() {
        return jtNombre.getText();
    }

    public String getCreditos() {
        return jtCreditos.getText();
    }

    public void borrarTxt() {
        jtNombre.setText("");
        jtCreditos.setText("");
        jtSiglas.setText("");
    }

    public void establecerNombre(String nombre) {
        jtNombre.setText(nombre);
    }

    public void establecerCreditos(String creditos) {
        jtCreditos.setText(creditos);
    }

    public void deshabilitarNombreCreditos() {
        jtCreditos.setEditable(false);
        jtNombre.setEditable(false);
    }

    public void habilitarNombreCreditos() {
        jtCreditos.setEditable(true);
        jtNombre.setEditable(true);
    }

    public void habilitarSiglas() {
        jtSiglas.setEditable(true);
    }

    public void desHabilitarSiglas() {
        jtSiglas.setEditable(false);
    }

    public boolean busquedaRealizada() {
        boolean variable = false;
        if (!jtNombre.getText().equalsIgnoreCase("")
                & !jtCreditos.getText().equalsIgnoreCase("")) {
            variable = true;
        }
        return variable;
    }

    public boolean verificarEntero() {
        try {
            Integer.parseInt(getCreditos());
            return true;
        } catch (NumberFormatException variable) {
            return false;
        }
    }

    public void msjNoEsEntero() {
        JOptionPane.showMessageDialog(null, "Ingrese créditos válidos", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void ingreseDatos() {
        JOptionPane.showMessageDialog(null, "Ingrese los datos para continuar");
    }
    public void msjEliminarExitoso() {
        JOptionPane.showMessageDialog(null, "Se ha eliminado exitosamente el curso");
    }

    public void msjRealiceBusqueda() {
        JOptionPane.showMessageDialog(null, "Realice una búsqueda previamente", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjDigiteSiglas() {
        JOptionPane.showMessageDialog(null, "Digite las siglas correctas", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjCursoNoEncontrado() {
        JOptionPane.showMessageDialog(null, "No se ha encontrado el curso", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjModificadoExitoso() {
        JOptionPane.showMessageDialog(null, "Se ha realizado la modificación exitosamente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSiglas = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlCreditos = new javax.swing.JLabel();
        jtSiglas = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCreditos = new javax.swing.JTextField();

        jlSiglas.setText("Siglas");

        jlNombre.setText("Nombre");

        jlCreditos.setText("Créditos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCreditos;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlSiglas;
    private javax.swing.JTextField jtCreditos;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtSiglas;
    // End of variables declaration//GEN-END:variables
}
