/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.RegistroCursos;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class PanelConsultarCursos extends javax.swing.JPanel {

    public static final String BOTON_CONSULTAR_SIGLA = "Consultar por sigla";
    public static final String BOTON_CONSULTAR_CURSOS = "Consultar cursos";
    public static final String BOTON_BORRAR = "Borrar";
    public static final String BOTON_CANCELAR = "Cancelar";

    /**
     * Creates new form PanelConsultarCursos
     */
    public PanelConsultarCursos() {
        initComponents();
        jtaDatosCursos.setEditable(false);
    }

    public void setManejador(ActionListener registroCursos) {
        jbBorrar.addActionListener(registroCursos);
        jbCancelar.addActionListener(registroCursos);
        jbConsultaSigla.addActionListener(registroCursos);
        jbConsultarCursos.addActionListener(registroCursos);
    }

    public String getSiglas() {
        return jtSiglas.getText();
    }

    public void BorrarTxt() {
        jtSiglas.setText("");
        jtaDatosCursos.setText("");
    }

    public void consultaCurso(RegistroCursos registroCursos) {
        jtaDatosCursos.setText(registroCursos.retornarCurso(jtSiglas.getText()));
    }

    public void consultaCursos(RegistroCursos registroCursos) {
        jtaDatosCursos.setText(registroCursos.getInformacion());
    }

    public void msjBorraSiglas() {
        JOptionPane.showMessageDialog(null, "Por favor borre las siglas para continuar", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjArrayVacio() {
        JOptionPane.showMessageDialog(null, "No existe información almacenada actualmente");
    }

    public void msjDigiteSiglas() {
        JOptionPane.showMessageDialog(null, "Por favor digite las siglas para continuar", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjIngreseSiglas() {
        JOptionPane.showMessageDialog(null, "Por favor ingrese las siglas para continuar", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjCursoNoEncontrado() {
        JOptionPane.showMessageDialog(null, "No se ha encontrado el curso", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlSiglas = new javax.swing.JLabel();
        jtSiglas = new javax.swing.JTextField();
        jbConsultaSigla = new javax.swing.JButton();
        jbConsultarCursos = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDatosCursos = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setText("Consultar cursos");

        jlSiglas.setText("Siglas");

        jbConsultaSigla.setText("Consultar por sigla");

        jbConsultarCursos.setText("Consultar cursos");

        jbBorrar.setText("Borrar");

        jbCancelar.setText("Cancelar");

        jtaDatosCursos.setColumns(20);
        jtaDatosCursos.setRows(5);
        jScrollPane1.setViewportView(jtaDatosCursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbConsultarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbConsultaSigla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbConsultaSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jbConsultarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConsultaSigla;
    private javax.swing.JButton jbConsultarCursos;
    private javax.swing.JLabel jlSiglas;
    private javax.swing.JTextField jtSiglas;
    private javax.swing.JTextArea jtaDatosCursos;
    // End of variables declaration//GEN-END:variables
}
