/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class PanelBusquedaEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form PanelBusquedaEstudiante
     */
    public PanelBusquedaEstudiante() {
        initComponents();
    }

    public String getNombre() {
        return jtNombre.getText();
    }

    public String getCarnet() {
        return jtCarnet.getText();
    }

    public void borrarTxt() {
        jtNombre.setText("");
        jtCarnet.setText("");
    }

    public void establecerNombre(String nombre) {
        jtNombre.setText(nombre);
    }

    public void deshabilitarCarnet() {
        jtCarnet.setEnabled(false);
        jtCarnet.setDisabledTextColor(Color.BLACK);
    }

    public void habilitarCarnet() {
        jtCarnet.setEnabled(true);
    }

    public void habilitarNombre() {
        jtNombre.setEnabled(true);
        jtCarnet.setEnabled(true);
    }

    public void deshabilitarJtext() {
        jtNombre.setEnabled(false);
        jtNombre.setDisabledTextColor(Color.BLACK);
        jtCarnet.setEnabled(false);
        jtCarnet.setDisabledTextColor(Color.BLACK);
    }

    public void msjEstNoEncontrado() {
        JOptionPane.showMessageDialog(null, "No se ha encontrado el estudiante", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjDigiteCarnet() {
        JOptionPane.showMessageDialog(null, "Digite un carnet válido", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjEliminado() {
        JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente el estudiante");
    }

    public void msjNoEntrado() {
        JOptionPane.showMessageDialog(null, "No se ha encontrado el estudiante a eliminar", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void msjModificadoExitoso() {
        JOptionPane.showMessageDialog(null, "Se ha realizado la modificación exitosamente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCarnet = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jtCarnet = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();

        jlCarnet.setText("Carnet");

        jlNombre.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jlCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCarnet;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextField jtCarnet;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
